basePath: /v1
definitions:
  apimodel.LoginParam:
    properties:
      password:
        example: "123456"
        type: string
      user:
        example: admin
        type: string
    required:
    - password
    - user
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: login param
        in: body
        name: loginParam
        required: true
        schema:
          $ref: '#/definitions/apimodel.LoginParam'
          type: object
      produces:
      - application/json
      responses:
        "200": {}
        "401": {}
      summary: user login
      tags:
      - login
  /logout:
    post:
      consumes:
      - application/json
      parameters:
      - description: bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
        "401": {}
      summary: user logout
      tags:
      - logout
swagger: "2.0"
